config/routes.rb
if Rails::VERSION::MAJOR >= 3
  RedmineApp::Application.routes.draw do
    #get '/groupext/menugroup' , :to 'groupext#menugroup', :as 'groupext'

    match 'groupext/menugroup',  :to => 'groupext#menugroup', :via => [:get, :post]
    match 'groupext/add_group_assignee/:group_id', :to => 'groupext#add_group_assignee', :via => [:get, :post], :as => :groupext_add_group_assignee
    match 'groupext/autocomplete_for_assigned/:group_id', :to => 'groupext#autocomplete_for_assigned', :via => [:get, :post], :as => :groupext_autocomplete_for_assigned
    match 'groupext/delete_group_assignee/:group_id/:user_id', :to => 'groupext#delete_group_assignee', :via => [:get, :post], :as => :groupext_delete_group_assignee
    match 'groupext/edit_groupassigne/:group_id', :to => 'groupext#edit_groupassigne', :via => [:get,:post] 

    
    match 'groupext/new',  :to => 'groupext#new', :via => [:get, :post]
    match 'groupext/update',  :to => 'groupext#update', :via => [:get, :post]
    match 'groupext/create',  :to => 'groupext#create', :via => [:get, :post]

  end
else
  ActionController::Routing::Routes.draw do |map|
    
    map.plugin_groups 'groupext/edit_groupassigne', :controller => "groupext", :action => 'edit_groupassigne'

    map.plugin_groups 'groupext/add_group_assignee', :controller => 'groupext',:action => 'add_group_assignee'
    map.plugin_groups 'groupext/autocomplete_for_assigned', :controller => 'groupext',:action => 'autocomplete_for_assigned'
    map.plugin_groups 'groupext/delete_group_assignee', :controller => 'groupext',:action => 'delete_group_assignee'

    map.plugin_groups 'groupext/menugroup', :controller => "groupext", :action => 'menugroup'
    map.plugin_groups 'groupext/new', :controller => "groupext", :action => 'new'
    map.plugin_groups 'groupext/update', :controller => "groupext", :action => 'update'
    map.plugin_groups 'groupext/create', :controller => "groupext", :action => 'create'

  end
end

app/models/groups_assigned.rb
class GroupsAssigned < ActiveRecord::Base
  belongs_to :group
  belongs_to :user
   
  def self.deleteAssignee(group_id,user_id)
    delete_all(:group_id => group_id, :user_id => user_id )
  end
  
end

app/controllers/groupext_controller.rb
require 'groups_helper'

class GroupextController < ApplicationController
  before_filter :require_group_assignee  
  helper GroupsHelper
  
  def new
    @group = Group.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @group }
    end
  end
  
  def create
    @group = Group.new(params[:group])

    respond_to do |format|
      if @group.save
        
        groupAssignee = GroupsAssigned.new
        groupAssignee.group_id = @group.id
        groupAssignee.user_id = User.current.id
        groupAssignee.save!
        
        format.html {
          flash[:notice] = l(:notice_successful_create)
          redirect_to(params[:continue] ?  { :controller => 'groupext', :action => 'new' } : { :controller => 'groupext', :action => 'menugroup' })
        }
        format.xml  { render :xml => @group, :status => :created, :location => @group }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def update
    @group = Group.find(params[:id])

    respond_to do |format|
      if @group.update_attributes(params[:group])
        flash[:notice] = l(:notice_successful_update)
        format.html { 
          redirect_to( :controller => 'groupext', :action => 'menugroup')
        }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit_groupassigne" }
        format.xml  { render :xml => @group.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  def autocomplete_for_assigned
    @not_in_assignees = User.active.not_in_group_assignees(params[:group_id]).like(params[:q]).all(:limit => 300)
    render :layout => false
  end
  
  def add_group_assignee
    Rails.logger.warn "add_group_assignee: params: " + params.to_s
    User.find_all_by_id(params[:user_ids]).each do |users|
      groupAssignee = GroupsAssigned.new
      groupAssignee.group_id = params[:group_id]
      groupAssignee.user_id = users.id
      groupAssignee.save!
    end          
 
    redirect_to edit_group_path(params[:group_id]) + '?tab=assignees'
  end
  
  def delete_group_assignee
    Rails.logger.warn "delete_group_assignee: params: " + params.to_s
    GroupsAssigned.deleteAssignee(params[:group_id],params[:user_id])
    
    redirect_to edit_group_path(params[:group_id]) + '?tab=assignees'
  end
  
  def menugroup
    @groups = Group.find(:all, :order => 'lastname')
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end
  
  def edit_groupassigne
	return nil if check_group_assignee(params[:group_id]) == false
	
    @group = Group.find(params[:group_id], :include => :projects)
    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @groups }
    end
  end

  def check_group_assignee(group_id)
	if !GroupsAssigned.find(:first, :conditions => ['user_id = ? and group_id = ?', User.current.id,group_id])
      render_403
      return false
    end
  end
  
  def require_group_assignee
    return unless require_login
    if !GroupsAssigned.find(:first, :conditions => ['user_id = ?', User.current.id]) and !User.current.admin? 
      render_403
      return false
    end
    true
  end 
end

app/helpers/groupext_helper.rb
require 'groups_helper'

module GroupextHelper
  def groupassinge_settings_tabs
    tabs = [ {:name => 'general', :partial => 'groupext/general', :label => :label_general},
             {:name => 'users', :partial => 'groups/users', :label => :label_user_plural}
           ]
  end

  def autocomplete_for_assigned(group)
	@not_in_assignees = User.active.not_in_group_assignees(group.id).like(params[:q]).all(:limit => 300)
	render :layout => false
  end
end

app/views/groupext/_assignee.html.erb
<div class="splitcontentleft">
 <% @in_assignees = User.active.in_group_assignees(@group.id) %>	
 <% if @in_assignees.any? %>
  <table class="list users">
    <thead><tr>
      <th><%= l(:label_user) %></th>
      <th style="width:15%"></th>
    </tr></thead>
    <tbody>
    <% @in_assignees.each do |user| %>
	  <% next unless user %>
      <tr id="user-<%= user.id %>" class="<%= cycle 'odd', 'even' %>">
        <td class="user"><%= link_to_user user %></td>
        <td class="buttons">
            <%= link_to l(:button_delete), groupext_delete_group_assignee_path(@group,user.id), :class => 'icon icon-del' %>
        </td>
      </tr>
	  <% end %>
    </tbody>
  </table>
<% else %>
  <p class="nodata"><%= l(:label_no_data) %></p>
<% end %>
</div>

<div class="splitcontentright">
<% @not_in_assignees = User.active.not_in_group_assignees(@group.id).all(:limit => 300) %>
<% if @not_in_assignees.any? %>

 <%= form_for(:groupext,  :url => groupext_add_group_assignee_path(@group),
               :html => {:method => :post}) do |f| %>
    <fieldset><legend><%=l(:label_user_new)%></legend>

    <p><%= label_tag "user_groupext_search", l(:label_user_search) %><%= text_field_tag 'user_groupext_search', nil %></p>
    <%= javascript_tag "observeSearchfield('user_groupext_search', 'groupext_users', '#{groupext_autocomplete_for_assigned_path(@group)}' )" %>

    <div id="groupext_users">
      &nbsp;
    </div>

    <p><%= submit_tag l(:button_add) %></p>
    </fieldset>
  <% end %>
<% end %>

</div>

app/views/groupext/_form.html.erb
<%= error_messages_for @group %>

<div class="box tabular">
  <p><%= f.text_field :lastname, :label => :field_name %></p>
  <% @group.custom_field_values.each do |value| %>
    <p><%= custom_field_tag_with_label :group, value %></p>
  <% end %>
</div>

app/views/groupext/_general.html.erb
<% labelled_form_for @group,:url => { :controller => 'groupext', :action => 'update',:id => @group.id} do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<%= submit_tag l(:button_save) %>
<% end %>

app/views/groupext/autocomplete_for_assigned.html.erb
<%= principals_check_box_tags 'user_ids[]', @not_in_assignees %>

app/views/groupext/edit_groupassigne.html.erb
<h2><%= link_to l(:label_GroupsAssignedsPlugin_groups), { :controller => 'groupext', :action => 'menugroup' } %> &#187; <%= h(@group) %></h2>

<%= render_tabs groupassinge_settings_tabs %>

<% html_title(l(:label_group), @group, l(:label_administration)) -%>

app/views/groupext/menugroup.html.erb
<div class="contextual">
<%= link_to l(:label_group_new), :controller => 'groupext', :action => 'new', :class => 'icon icon-add' %>
</div>

<h2><%= l(:label_group_plural) %></h2>
<% if @groups.any? %>
<table class="list groups">
  <thead><tr>
  <th><%=l(:label_group)%></th>
  <th><%=l(:label_user_plural)%></th>
  <th></th>
  </tr></thead>
  <tbody>
<% @groups.each do |group| %>
  <% if User.current.assignee?(group.id) %>
  	<tr class="<%= cycle 'odd', 'even' %>">
      <td align="center">
	        <%= link_to h(group), :controller => 'groupext', :action => 'edit_groupassigne', :group_id => group.id  %>
			</td>
      <td align="center"><%= group.users.size %></td>
   </tr>
  <% end %>
<% end %>
</table>
<% else %>
<p class="nodata"><%= l(:label_no_data) %></p>
<% end %>

app/views/groupext/new.html.erb
<h2><%= link_to l(:label_GroupsAssignedsPlugin_groups), { :controller => 'groupext', :action => 'menugroup' } %> &#187; <%= l(:label_group_new) %></h2>
<% labelled_form_for @group, :url => { :controller => 'groupext', :action => 'create' } do |f| %>
<%= render :partial => 'form', :locals => { :f => f } %>
<p>
  <%= f.submit l(:button_create) %>
  <%= f.submit l(:button_create_and_continue), :name => 'continue' %>
</p>
<% end %>